cloud-gov/pages-redirects

- package.json
- yarn.lock
> use tap-summary instead of faucet

- .travis.yml
- README.md
- deploy-travis.sh
> setup automated deploy

- docker-compose.yml
- lib/index.js
- package.json
- pages.yml
- templates/nginx.conf.nj
- test/integration/test_server.js
- test/unit/test_lib.js
> Add existing pages.18f.gov redirects from federalist-redirects

- README.md
> Finish up integration test documentation in README

- README.md
- lib/index.js
- templates/nginx.conf.njk
- test/unit/test_lib.js
Closes #25 
I misnamed the branch 😞
> Add toDomain config setting

- templates/nginx.conf.njk
- test/integration/test_pages_redirects.js
> allow internal http redirect in some tests

- test/integration/test_docker_config.js
> Add tests to make sure docker-compose external_links are setup

- templates/manifest-prod.yml.njk
> add join.18f.gov to routes for migration

- templates/manifest-prod.yml.njk
> add guides.18f.gov to routes

- templates/manifest-prod.yml.njk
> Add pages.18f.gov to routes

- pages.yml
Redirect entry for pages.18f.gov/ads-bpa to ads.18f.gov
> Redirect for ads-bpa to ads

- README.md
> Add info about handling old federalist-redirects to README

- pages.yml
updating per instructions in migration document
> updating to add agile.18f.gov

- pages.yml
redirect from E/W pages to govCloud federalist
> redirect for agile-labor-categories site

- pages.yml
This changeset adds the guides-template redirect.
> Add guides-template redirect

- pages.yml
Adds the redirect for the blogging guide.
> Add blogging guide

- pages.yml
OLD: https://pages.18f.gov/brand/
NEW: https://brand.18f.gov/
Not sure if I did this right
> Adding visual identity site redirect

- pages.yml
Added redirect for product guide
> Added product guide

- pages.yml
/cc https://github.com/18F/before-you-ship/pull/302
> redirect Before You Ship

- pages.yml
Added redirect code for https://pages.18f.gov/design-principles-guide/ to go to design-principles-guide.18f.gov
> added design principles guide

- pages.yml
Add redirect from [pages.18f.gov](https://pages.18f.gov/accessibility/) to [accessibility.18f.gov](https://accessibility.18f.gov).
> add accessibility redirect

- pages.yml
Add redirects:
* [pages.18f.gov/testing-cookbook](https://pages.18f.gov/testing-cookbook/) to [testing-cookbook.18f.gov](https://testing-cookbook.18f.gov)
* [pages.18f.gov/automated-testing-playbook](https://pages.18f.gov/automated-testing-playbook/) to [automated-testing-playbook.18f.gov](https://automated-testing-playbook.18f.gov)
> add testing cookbook and playbook redirects

- README.md
- lib/index.js
- pages.yml
- templates/nginx.conf.njk
- test/integration/test_pages_redirects.js
- test/unit/test_lib.js
I added some explicit tests because I think these are non-standard cases
> Add some more redirects for additional identity-* repos

- pages.yml
api-program; api-all-the-x; api-usability-testing; open-source-guide; open-source-program; slides
> adding 6 sites

- pages.yml
Made changes to the two URLs for these two sites.
> innovation-toolkit-prototype

- .circleci/config.yml
> update circle deployment script name in circleci config

- templates/manifest-prod.yml.njk
> test removal

- templates/nginx.conf.njk
- test/integration/test_pages_redirects.js
Reverts 18F/pages-redirects#106
> Revert "test"

- templates/manifest-prod.yml.njk
> added route: demo.digitalgov.gov

- docker-compose.yml
- templates/_federalist-redirects.njk
- test/integration/test_federalist_redirects.js
> Blogging redirect test case

- docker-compose.yml
- templates/_federalist-redirects.njk
> Redirect dated 18F microsites

- build.js
- lib/index.js
- mime.types
- templates/manifest-prod.yml.njk
- templates/nginx.conf.njk
- test/unit/test_lib.js
> init nginx-buildpck migraton

- .circleci/config.yml
- docker/Dockerfile-test_client
- package.json
- yarn.lock
> upgrade to node 10

- docker-compose.yml
- templates/_federalist-redirects.njk
These sites were archived by outreach team: https://docs.google.com/spreadsheets/d/1p39U0KNi1tV2laNZORQ3uchBFvEZlUmIgv9DXyBMlqg/edit#gid=0
> Redirect additional 18f microsites

- docker-compose.yml
- templates/_federalist-redirects.njk
Reverts 18F/pages-redirects#118
> Revert "Revert "Redirect additional 18f microsites""

- pages.yml
> temporarily remove routes to allow creation of domains

- docker-compose.yml
- pages.yml
- templates/_federalist-redirects.njk
> add redirects to github

- docker-compose.yml
- templates/_federalist-redirects.njk
> add apply.gif w/o route

- templates/manifest-prod.yml.njk
> add apply.pif.gov to routes

- templates/_federalist-redirects.njk
- test/integration/test_federalist_redirects.js
> add test for apply.pif.gov

- pages.yml
> temp remove modularcontracting route

- pages.yml
Reverts 18F/pages-redirects#128
> Revert "temp remove modularcontracting route"

- templates/manifest-prod.yml.njk
> update manifest to stack cflinuxfs3

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- test/integration/test_federalist_redirects.js
> HOLD: v2.designsystem.digital.gov to designsystem.digital.gov

- .eslintrc
- .eslintrc.js
- package.json
- yarn.lock
> update packages w/ securrity conerns

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- test/integration/test_federalist_redirects.js
> archive sites

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
> add agile-bpa

- pages.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
https://gsa-tts.slack.com/archives/C1NUUGTT5/p1567793352016500
> remove paid-leave-prototype

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
> redirect onepage slides and fedspending to github

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- test/integration/test_federalist_redirects.js
> redirect findtreatment.gov

- README.md
> Redirect steps

- .circleci/config.yml
- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
Configured as a new "Domain redirect".
> Add redirect for federalist-docs.18f.gov to federalist.18f.gov

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- test/integration/test_federalist_redirects.js
> HOLD: redirect handbook

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- test/integration/test_federalist_redirects.js
> Redirect frontend.18f.gov

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
> redirect proposal.pif.gov to gogole form

- templates/_federalist-redirects.njk
> fiz proposoal.pif.gov target

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
> redirect federalist-report-template.18f.gov to github repo

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- test/integration/test_federalist_redirects.js
> redirect www.search.gov to search.gov

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
> redirect ads and paid-prototype to repos

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- test/integration/test_federalist_redirects.js
> add usability.gov

- templates/_federalist-redirects.njk
> set hsts header for usability.gov preload

- templates/_federalist-redirects.njk
- test/integration/test_federalist_redirects.js
fix tests for emerging.digital.gov
> Sc redirect emerging - fix tests

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- test/integration/test_federalist_redirects.js
Redirect https://emerging.digital.gov/ to https://digital.gov/topics/emerging-tech/
> Redirect emerging.digital.gov

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
(looks like I didn't have access to make a branch in the PR, so I had to clone to personal)
> Add redirect configs for developer{ => s}.login.gov

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- test/integration/test_federalist_redirects.js
Resolving issue https://github.com/18F/dns/issues/482
> redirect components.designsystem.digital.gov to designsystem.digital.gov/components/

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
> redirect climate-data-user-study.18f.gov to github repo https://github.com/18F/climate-labs

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
> add redirect for c2.18f.gov to google form

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- test/integration/test_federalist_redirects.js
> remove demo.digitalgov.gov

- .circleci/config.yml
- README.md
- deploy-ci.sh
https://github.com/18F/tts-tech-portfolio/issues/519
Rename default branch master -> main
> Update default branch

- pages.yml
related to https://github.com/18F/dns/issues/525
> redirect agile-labor-categories to agile.18f.gov

- docker-compose.yml
- pages.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
> Redirect status.login.gov to our statuspage.io page

- docker-compose.yml
- pages.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
This reverts commit 8ab910db0e9c81af77162ca0a660c175e7acd66a, reversing
changes made to fcf89b5a41be308f19475e059ef18bc510726fe6.
> Revert "Merge pull request #189"

- .circleci/config.yml
- docker-compose.yml
- docker/Dockerfile-test_client
- package.json
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- yarn.lock
- Wait on https://github.com/18F/dns/pull/610 to be deployed before merging
- Add redirect for fac.gov to www.fac.gov
> feat: Add fac.gov redirect to www.fac.gov

- templates/_federalist-redirects.njk
- Add redirects for guides.18f.gov
none
> Guides.18f.gov redirects

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- Re-enables atf-eregs redirect
none
> Feat: Re-enable atf-eregs redirect

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
Closes #246 and #247
- Adds redirect for identityequitystudy.gsa.gov
None
> feat: Add identityequitystudy.gsa.gov redirect

- templates/_federalist-redirects.njk
- Adds two additional redirects for join.tts.gsa.gov
None
> feat: Add additional join.tts.gsa.gov redirects

- package-lock.json
- templates/_federalist-redirects.njk
- Updates redirects to use `$request_uri`
None
> fix: Update applicable redirects to use $request_uri

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- Setup redirect for fehrm.gov apex to www
None
> feat: Add fehrm apex to www redirect

- docker-compose.yml
- templates/_federalist-redirects.njk
- templates/manifest-prod.yml.njk
- test/integration/test_federalist_redirects.js
- Removes the www.search.gov redirect
N/A
> feat: Remove www.search.gov redirect
