.travis.yml, build-nginx-configs.js, lib/index.js, pages.yml, test/integration/test_server.js, test/unit/test_lib.js, test/unit/test_pages_config.yml
Closes #6 
I've also changed `getPageConfigs` to take a yaml-string instead of a file path. This allows better testing since I don't need to have a file to load.
=> Remove test pages.yml configs

docker-compose.yml, templates/_federalist-redirects.njk, test/integration/test_federalist_redirects.js
Closes #31 
Previously `login.gov` and `www.login.gov` would redirect to `pages.18f.gov/identity-intro`. This PR removes that redirection.
=> Remove login.gov redirects

templates/manifest-prod.yml.njk
Also remove pages-staging and guides-staging routes. They are unused.
=> Add jobs.18f.gov route

.travis.yml
This PR install yarn from apt, which is [recommended](https://yarnpkg.com/en/docs/install#linux-tab) over using `npm install -g yarn`.
I had tried using the "built-in" version of `yarn` that Travis already has, but it is a fairly old version (`0.17.8`). Current stable version is `0.23.2`.
Closes #38
=> Install yarn from apt

test/integration/test_federalist_redirects.js
Fixes #48 
When `TARGET_HOST` is set and starts with `https`, then the integration tests are being run against a real server. This PR adjusts the test requests to use `https` in that case.
=> Run integration tests over https when TARGET_HOST is set

pages.yml
This changeset adds a redirect for the `fec-style` site (https://fec-style.18f.gov/) and the `GovConnect` site (https://govconnect.18f.gov/).  Thanks!
=> Add fec-style and govconnect redirects

templates/nginx.conf.njk, test/unit/test_lib.js
Updates the `nginx.conf` template to require a leading slash before a subpath, if any, to help prevent a shorter domain eating a larger.  For example, with the previous template, an entry in `pages.yml` that just says `agile` would also generate this config line:
```
rewrite ^/agile(.*)$ https://agile.18f.gov$1;
```
This would also match `/agile-labor-categories`, which would then result in an incorrect redirect, on two fronts.  First, it would redirect to `agile.18f.gov` instead of `agile-labor-categories.18f.gov`.  Second, it would match the latter part as a subpath (`-labor-categories`) and append that, making the new whole redirect `https://agile.18f.gov-labor-categories`).
This PR updates the config such that the subpath is still optional, but if present, it must include a leading …
=> Fix to make the nginx config agnostic to pages.yml order

docker-compose.yml, pages.yml, templates/manifest-prod.yml.njk, templates/nginx.conf.njk, test/integration/test_pages_redirects.js
Context: https://github.com/18F/guides/issues/51
After this, guides.18f.gov should act like any other redirect
=> [needs review] remove guides and treat as any other app

templates/nginx.conf.njk, test/integration/test_pages_redirects.js
Pages without a trailing slash are supposed to redirect to the page with a trailing slash. For example `page.18f.gov/lean-product-design` should redirect to `pages.18f.gov/lean-product-design`.
Unfortunatly, the redirect above was pointing to `pages-redirects.apps.cloud.gov/lean-product-design` since there was no hostname in the target for the rewrite. This commit adds a hostname to the target.
=> Add hostname to redirects for non-migrated pages w/o a trailing slash

README.md
Oops, I forgot to update the README as part of #80. This PR updates the build status badge and other references of Travis to CircleCI.
=> Update build badge and ci references to CircleCI

templates/nginx.conf.njk, test/integration/test_pages_redirects.js
All 18F Pages have now been migrated and Federalist is moving from E/W to GovCloud, so the old S3 bucket will soon be shut down.
The error page is very simple. It looks like this:
=> Show an error page for any request not covered by a redirect

pages.yml
This changeset removes the redirect to `fec-style` is that is now an old guide that we will not be publishing via pages anymore.  The new guide is hosted on cloud.gov.
=> Remove old fec-style guide

pages.yml, templates/nginx.conf.njk, test/integration/test_pages_redirects.js, test/unit/test_lib.js
so that requests of the form pages.18f.gov/CasedName will still work
Also:
- Remove now unnecessary "API-All-the-X" config
- Remove spurious tests from change in #75 that were never actually run
=> Make rewrite regex case-insensitive

templates/_federalist-redirects.njk, test/integration/test_federalist_redirects.js
Lots of users looking for connect.ct.gov are confused when connect.gov
takes them to login.gov. We expect to eventually remove this redirect in
favor of a Federalist site explaining connect.gov to users and providing
them links to get where they want to go.
=> Redirect connect.gov to connect.ct.gov

docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk, test/integration/test_federalist_redirects.js
Before we launch https://github.com/18F/pages-redirects/pull/101
We are testing with a subdomain.
---
=> Test redirect for demo.digitalgov.gov

docker-compose.yml, pages.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk
Redirect blogging guides subdomain to handbook. We only need to redirect the domain not the URI request.
=> Redirect blogging guides subdomain to handbook.

docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk, test/integration/test_federalist_redirects.js
=> remove redirects for www.app.gov and app.gov

docker-compose.yml, templates/_federalist-redirects.njk
- in part of the modular contracting sunset - noted in the draft post here: https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/modular-contracting/2019/04/09/why-we-love-modular-contracting/,
We will be archiving the site in favor of the repository
=> Add redirect for modular contracting

templates/_federalist-redirects.njk
This is for fixing https://github.com/GSA/digitalgov.gov/issues/1007 — _"Domain is no longer HSTS preloading"_
---
=> header strict-transport-security to digitalgov.gov

docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk
Part of https://github.com/18F/tts-micropurchase-bots/issues/30.
Hey hey- What needs to happen beyond this? Presumably a [DNS](https://github.com/18F/dns/blob/master/terraform/18f.gov.tf) change? Are those steps written up anywhere?
=> redirect C2 to Handbook

docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk, test/integration/test_federalist_redirects.js
=> remove jobs/join.18f.gov - redirect handles in 18f/dns

templates/_federalist-redirects.njk
=> remove hsts for usability.gov

docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk
these domains no longer have DNS entries
=> remove non-existent federalist templates domains

docker-compose.yml, templates/manifest-prod.yml.njk
cleanup -- connect.gov is no longer owned by TTS
=> remove connect.gov

docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk
Decommissioning govconnect.18f.gov based on https://github.com/18F/tts-tech-portfolio/issues/1027
=> Update config to redirect govconnect.18f.gov to github repo

docker-compose.yml, pages.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk
This reverts commit a2a13cb7d69ac691b89467e019899f34351330e6, reversing
changes made to eb27629e067224976470df6d02550f6f5a431c3e.
[Error in CI](https://app.circleci.com/pipelines/github/18F/pages-redirects/85/workflows/cc0c7a77-eca7-4321-828c-496217dd46c9/jobs/331):
> error: The route www.logingov.statuspage.io did not match any existing domains.
=> Revert "Merge pull request #187"

docker-compose.yml, pages.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk
Redo of #187 now that we have the right DNS stuff in place already
This reverts commit fcf89b5a41be308f19475e059ef18bc510726fe6, reversing
changes made to a2a13cb7d69ac691b89467e019899f34351330e6.
=> Redirect status.login.gov

docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk
Cannot create the redirect until the existing one is removed from the atf eregs cloud.gov org.
=> Remove redirect for atf-eregs for now

docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk
Redirect paygap.pif.gov and tophealth.pif.gov to pif.gov
=> Add redirects for paygap.pif.gov and tophealth.pif.gov

templates/_federalist-redirects.njk
`pif.gov` will now have
```
add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';
```
which it hitherto lacked.
=> Add STS header for pif.gov

templates/_federalist-redirects.njk
- Add Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload' to www.search.gov
=> Add include subdomains preload to www.search.gov

docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk
Related: https://github.com/18F/dns/issues/599
=> Redirect portfolios.18f.gov to 18f.gsa.gov.

README.md, docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk, test/integration/test_federalist_redirects.js
The site https://partners.login.gov is hosted on Federalist, but now redirects to its new location at https://login.gov/partners . This is currently implemented using static site redirects through HTML markup (`<meta http-equiv="refresh">` via [`jekyll-redirect-from`](https://rubygems.org/gems/jekyll-redirect-from), [see example page source](https://github.com/18F/identity-partners-site/blob/main/_pages/index.md)).
The changes proposed here would create proper 301 redirects for the domain and a set of paths, allowing us to decommission the site in the Federalist dashboard. 
* https://partners.login.gov/ :arrow_right: https://login.gov/partners/
* https://partners.login.gov/product/ :arrow_right: https://login.gov/partners/our-services/
* https://partners.login.gov/sandbox/ :arrow_right: …
=> Add partners.login.gov redirect configuration

docker-compose.yml, templates/_federalist-redirects.njk
- Add redirect for federalistapp.18f.gov to pages.cloud.gov
Redirect for deprecated endpoints
=> feat: Add redirect for fedearlistapp.18f.gov to pages.cloud.gov

templates/manifest-prod.yml.njk
- Remove old federalist-docs.18f.gov redirect
Deprecated URL
=> chore: Remove federalist-docs.18f.gov redirect

docker-compose.yml, templates/_federalist-redirects.njk, test/integration/test_federalist_redirects.js
Adds configuration to redirect https://design.login.gov to https://www.login.gov
Similar to previous #200
N/A
=> Add design.login.gov redirect configuration

docker-compose.yml, templates/_federalist-redirects.njk, test/integration/test_federalist_redirects.js
- Adds configuration to redirect https://design.login.gov to https://www.login.gov
- Similar to previous #200
Adding redirect
=> Signed add design.login.gov redirect configuration

templates/_federalist-redirects.njk
- Redirect any request to the plain guides.18f.gov to 18f.gsa.gov/guides/ (the current landing page for all guides)
- Redirect any request to a specific guide using the new URLs to the existing guide pages, eg:
`guides.18f.gov/<guide-name>/` redirects to `<guide-name>.18f.gov/`
- If there is any extra part to the URL in a specific guide, ensure that it is trimmed and passed on to the existing guide upon redirect
I am not aware of any security concerns, but could use a review of the nginx syntax
https://github.com/18F/TLC-crew/issues/428
=> Update guides.18f.gov with temporary redirects

docker-compose.yml, pages.yml, templates/_federalist-redirects.njk, templates/nginx.conf.njk, test/integration/test_pages_redirects.js
- Removes guides.18f.gov from the redirects
None
=> chore: Remove guides.18f.gov

templates/_federalist-redirects.njk
- Permanently redirect all requests to `agile.18f.gov` to `guides.18f.gov/agile`
- Ensure that additional sub-paths are passed correctly during the redirect, ie `agile.18f.gov/something-here` redirects to `guides.18f.gov/agile/something-here`
There are no known security considerations
=> Updating agile guide subdomain requests to redirect and rewrite

docker-compose.yml, templates/_federalist-redirects.njk
- Adds 301 redirects for pages on `brand.18f.gov` to `guides.18f.gov/brand/`, similar to #226 
- Adding `brand.18f.gov` to `docker-compose.yml` made all integration tests pass
None
=> Permanently redirect 18F brand guide to guides.18f.gov/brand (main branch)

docker-compose.yml, templates/_federalist-redirects.njk
Adds 301 redirects for:
- `accessibility.18f.gov`
- `eng-hiring.18f.gov`
- `engineering.18f.gov`
- `product-guide.18f.gov`
Also makes integration tests pass with new redirects.
None
=> Permanently redirect 18f guides: accessibility, eng-hiring, engineering and product

docker-compose.yml, templates/_federalist-redirects.njk
Adds 301 redirects for:
- `accessibility.18f.gov`
- `eng-hiring.18f.gov`
- `engineering.18f.gov`
- `product-guide.18f.gov`
Also makes integration tests pass with new redirects.
None
=> redirect 18f guides: accessibility, eng-hiring, engineering and product

docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk
- re-enable the permanent redirect from https://atf-eregs.18f.gov/ to https://regulations.atf.gov/ 
- None
=> re-enable atf-eregs redirect

ci/docker/entrypoint.sh, ci/pipeline.yml
Closes #236 
- Adds hardened node, time, git, and docker in docker (dind) images to the resource types and tasks in CI
Add hardened resource type images to CI.
=> chore: Update CI to use hardened resource images

ci/pipeline.yml
Related to https://github.com/cloud-gov/pages-core/issues/4394
- Switches to use the general-task image
- Adds registry-image resource type
Related to adding hardened containers
=> chore(ci): Switch to general-task and registry-image for CI jobs

ci/partials/build.yml, ci/partials/install-dependencies.yml, ci/pipeline.yml
- Refactors pipeline to use the latest functionality from pages-pipeline-tasks
- Removes redundant task code and config for node install and builds
- Creates two deploy envs `dev` and `deploy` that are set via the boot task's `ENV_OVERRIDE`
None
=> chore(ci): Refactor the ci pipeline to improve dry-ness

ci/pipeline.yml
- Adds CF_APP_NAME param to successfully run nightly restage task
None
=> fix(ci): Add CF_APP_NAME param to nightly restage task

docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk, test/integration/test_federalist_redirects.js
- Adds redirects for join.tts.gsa.gov
None
=> feat: add join.tts.gsa.gov redirects

docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk
In favor of #260 
- Adds demo.pra.digital.gov redirect to pra.digital.gov
None
=> feat: Add demo.pra.digital.gov redirect to pra.digital.gov

docker-compose.yml, templates/_federalist-redirects.njk, templates/manifest-prod.yml.njk
- Add code.gov, www.code.gov, staging.code.gov, api.code.gov redirects to digital.gov
Adds redirects
=> feat: Add code.gov redirect to digital.gov

templates/_federalist-redirects.njk
- Switch code.gov redirects from digital.gov to digital.gov/resources/requirements-for-achieving-efficiency-transparency-and-innovation-through-reusable-and-open-source-software/
None
=> chore: Switch code.gov redirects destination

docker-compose.yml
- Removes federalistapp.18f.gov redirect since it is deprecated.
Removing deprecated redirect.
=> chore: Remove federalistapp.18f.gov redirect
